### PR TITLE
Renamed all ServiceBus references to EventHubs

### PR DESCRIPTION
**Pull request by jtaubensee**
## Description
Addresses #95.

This PR renames all Service Bus references to Event Hubs. This includes:
* Package names
* ServiceBusException -> EventHubsException
* Trace names

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](./CONTRIBUTING.md).**
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR.
- [ ] The pull request does not introduce breaking changes (unless a major version change occurs in the assembly and module).
- [x] If applicable, the public code is properly documented.
- [x] Pull request includes test coverage for the included changes.
- [x] The code builds without any errors.

### CODE REVIEW

**Comment by jtaubensee** [comment]
Still need to fix the samples for the build to pass.

**Comment by Blackbaud-AdiSaraf** [comment]
Hi @jtaubensee,
Any ideas when this PR will be merged? We have been waiting for this separation for a long time and I believe it was slated for Milestone 1.0.0. Any ideas on the date of this Milestone release?

Thanks!

**Comment by SreeramGarlapati** [comment]
Hi @Blackbaud-AdiSaraf, 
as this PR has a lot of breaking changes... we are still figuring out the dates - I will keep you posted...
Apologies to keep you waiting...

**Comment by kevinhartman** [comment]
We need this as well (internal MS). Please expedite this if possible.

**Comment by SreeramGarlapati** [comment]
Hello @jtaubensee - how r u!
Sorry that I had to send a brand new PR - which felt easier than merging all the conflicts...

**Pull request closed without merging**
