### PR TITLE
update dependency versions - proton-j & storage client

### PR DESCRIPTION
**Pull request by SreeramGarlapati**

### CODE REVIEW

**Comment by SreeramGarlapati** [comment]
@jtaubensee  -  can you please use your powers to push this through...

**Comment by jtaubensee** [comment]
@SreeramGarlapati - Shouldn't this be merged into dev, rather than master?

**Comment by SreeramGarlapati** [comment]
oh.. yeah..
Sent this PR before our yesterday's dev branch reset..

**Comment by jtaubensee** [comment]
ok - we can actually just update the branch in the PR

**Pull request merged**
